// <auto-generated />
namespace C.M_HelpLine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6));
        
        string IMigrationMetadata.Id
        {
            get { return "202203030429147_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
